version: "3"

volumes:
  esdata01:
    driver: local

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /opt/nifi_demo/mongo-data:/data
      - /opt/nifi_demo/mongo:/opt/nifi_demo
